### ISSUE TITLE
This currently doesn't work

### ISSUE THREAD

**Issue by porky11** [vadixidav/zoomtest#1]
First error:
```
  --> src/main.rs:13:10
   |
13 | use na::{ToHomogeneous, Translation, Rotation};
   |          ^^^^^^^^^^^^^ no `ToHomogeneous` in `na`
```

**Comment by vadixidav** [comment]
ill take care of that

**Comment by vadixidav** [comment]
Alright, I did not update the dependencies of zoomtest, however I did change the Cargo.toml to use the specific versions which it was written with, rather than using a wildcard. These days I would have never done that. Sorry about that.
